language: python
python:
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
env:
  global:
    # Doctr deploy key for ke-zhang-rd/krystal
    - secure: "gAzOOXrx+hn+fkx6+KQA84SeKTV1hZ91ISYDxHjzAr+5gpPIKNz2SEpbGNhCQagOTjTmSzmsPFlEoqkWfwUr1cUA97eu2nC5q+YoXMZq1PjEQBKHJgQnDfaICwC49/z3UVl/XNrenYt1xIDH5HScc63L0qTzWYj8cPMrwmxVhtY5oUq7JnpjolyslRo5FsW+D0YlJwrY8U3RBcz3S4DkBs1hhF5zzJK40+LGyQgVcdV4rY4/foJdf2/yL/sRe0gICdcDAXIY9tLlTO0lwOl5sIi51FLSQsBLAxSZEwiTXbR9IzRUvI6WNwBUvAAtbU517JlZuKOknV1WHqjTWSW4++hJSiJXFUpHBQjhJxNZA10l8AMM/f3NUnTVL21VJtfEYw+9cmFyLFtiyOvVYjJhiQ2Vw9vo5W2E62XN4IrDjolmOr1Xq4cPujgQuv++Iyv1XouK392xfCLk5ah2Hgx82DxHUtNlkChYg+1XL8L8kA90ygtL85uxMY86Y+AdMma8OnJMWbZF0fowgEBwuI1LR9IOHCLLn5n8a92+S/M4Tyyn9VGABbdoigy3yeTFXdZ6hpEB1yVMESOkhrzQ6ius0hXATiL+58O5OWDfF9Q95xpy8oG2oOswN8f1zk7ox0LX9Y3+p3qWlkN1DGaqKIQhpcv9H+t+VeCO1oaug1Y6IHg="

install:
  # The versions of pip and numpy that come pre-installed are often too old and
  # can cause problems. Upgrade them.
  - pip install --upgrade pip numpy
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - set -e  # If any of the following steps fail, just stop at that point.
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .  # Publish the documentation.
