language: python
python:
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
env:
  global:
    # Doctr deploy key for ke-zhang-rd/krystal
    - secure: "pGwQlobJRlacfQeLJydwLdxYHE/6qttWuNYhJ2DxkNiurhQ8sE0PR/uBobgQTC/jnC0T+x/YATMMsBPPIT20Ko+k9P0clp8Bbm+FS0ATLsNci7HhRfFhmS5wypLYSSA2yV8EeLiSgVU522g0uit5WqmPKCwWOob1dghkadGJaIKA3oTMNmctKSEIykmOC+cdMgAkx5iJIb/H3XLL/TwDqPRd+f0GU9mnqy9mbQJ8tDn7KriJNBZHXW+fyDETshUw1oT44rzc/RJf8C58yZCv1F/d8BQil4eqwaUJSajr5DbX7OXJxs0XMdUYb52RnkbApZRrhz5kpgIqH+ocGKkR4XmB6CgLnkOeIa7aVFr3QTcBS9NfnwV/C+8iXmuHVgwKJ8/s4dEgFl2zt2P0irnuU2BHeWZANelx/jjKnFoK1uUJ32wHDZ82DEGqJq8mVEVDAz4SzgxbDgHlCZ/A1wItqPu/Mkpk9C7P3L5bN/tz1dGX3xvDGJF7p9/eGMjzv7kJG7k0O/O3KTXm5QIBeQaGk/JrxCtk29Uplf4tLYJE1fxXKRij6QBXf46qUuNc3uJ7O5QGFxDDtw1TA3Giu8J7/FxxkTCVfKR04C5XxNrX3njTCEKDSpCkqaoQ7WqBg/ZMFRv/34Kf/kbEbBQ+72Ao+VkPgWPjZbrs5X9UJ+pjSy8="

install:
  # The versions of pip and numpy that come pre-installed are often too old and
  # can cause problems. Upgrade them.
  - pip install --upgrade pip numpy
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - set -e  # If any of the following steps fail, just stop at that point.
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .  # Publish the documentation.
